### PR TITLE
Revert "Develop"

### PR DESCRIPTION
**Pull request by mzy2240**
Reverts mzy2240/ESA#59 because the original pull request fails to pass the test

### CODE REVIEW

**Comment by mzy2240** [comment]
@blthayer I revert the pull request cause it fails to pass the test _test_get_power_flow_results_with_commas_

**Comment by mzy2240** [comment]
Oops, I think I revert the wrong commit. The current develop branch cannot pass the test.

**Comment by mzy2240** [comment]
That's weird. From the changed files I revert the correct commits, but it automatically merged into master branch.

**Comment by blthayer** [comment]
@mzy2240 - that test you mentioned was passing when it was run individually, but not when the entire suite was run. Turns out, there was a small bug in saw.py that was causing that. I fixed it in eb517bd88e36e10a795f181b6551ca70fd9dda7b

**Comment by blthayer** [comment]
@mzy2240 - could you merge develop into master now and push the release?

**Pull request merged**
